# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

superpowers = Power.create([
  {name: "Speed", description: "Users can move much faster than the average member of their species, beyond what can be emulated via natural training and with little to no maintaining. However, this power is not without any ill effects, as it can strain the body, although some users may be resistant or even immune to the effects of high-speed travel, including acceleration, friction, g-force, inertia, etc. They are able to run from about 64-193 kph which means they can reach subsonic speeds."},
  {name: "Strength", description: "Users possess a level of strength beyond that of the peak members of their specie and usually in their Verse. At base level, users would be able to lift heavy objects such as cars, large boulders, vans, and most other objects that are bigger than them in size. They would also be able to exert great physical force from various parts of their body (prominently through their hands), sending enemies flying through walls or breaking their bones instantly with a single punch."},
  {name: "Invisibility", description: "Users can render themselves unseen by the naked eye and become invisible in visible spectrum. The user can move about an environment unseen by others and act without being observed. Some users can choose to let certain people see them, while staying invisible to others."},
  {name: "Shape Shifting", description: "Users can shapeshift, changing their form and appearance at will, maybe even transforming and reshaping themselves down to their genetic and cellular structure. They can impersonate others or enhance their own body for combat, either by turning into animals, humanoids, monsters, etc. or by making the body stronger."},
  {name: "Teleportation", description: "The users can teleport; moving instantaneously from one location to another without physically occupying the space in between or transfer matter (beings/objects, including themselves) or energy from one point to another without traversing the physical space between them. This can be achieved by various means, including causing the atoms/molecules to travel at light-speed, warping the space, or use quantum superposition, in which the user teleports by spatially rearranging the subatomic contents of a system."},
  {name: "X-Ray Vision", description: "The user can see x-rays, electromagnetic waves of high energy and very short wavelength, which is able to pass through many materials opaque to light. This can be used for medical purposes such as the detection of cancers, tumors, blackened lungs, etc. The skill of perceiving a specific location (i.e. artery) is given by partial reflection of the ray from each specific surface surveyed."},
  {name: "Magic", description: "Users are able to utilize magic, the use of rituals, symbols, action, gestures, language, etc., to exploit supernatural forces to varying degrees, with only their skill, personal power-level, imagination/knowledge, and/or morality to define the borders. Given the flexibility of magic and their ability to transcend logic, laws, and common sense, its users have essentially limitless possibilities for what they can accomplish and achieve, capable of altering reality through their gifts."},
  {name: "Shape Shifting", description: "Users can shapeshift, changing their form and appearance at will, maybe even transforming and reshaping themselves down to their genetic and cellular structure. They can impersonate others or enhance their own body for combat, either by turning into animals, humanoids, monsters, etc. or by making the body stronger."},
  {name: "Shape Shifting", description: "Users can shapeshift, changing their form and appearance at will, maybe even transforming and reshaping themselves down to their genetic and cellular structure. They can impersonate others or enhance their own body for combat, either by turning into animals, humanoids, monsters, etc. or by making the body stronger."},
  {name: "Shape Shifting", description: "Users can shapeshift, changing their form and appearance at will, maybe even transforming and reshaping themselves down to their genetic and cellular structure. They can impersonate others or enhance their own body for combat, either by turning into animals, humanoids, monsters, etc. or by making the body stronger."}
  ])
